blog/urls.py
from django.urls import path
from .feed import LatestPostFeed
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('recent-posts/', views.recent_post, name='recent_post'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search-post/', views.search_post, name="search_post"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.conf import settings
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
         name="django.contrib.sitemaps.views.sitemap")
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.db import models
from django.utils import timezone
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    tags = TaggableManager()
    
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    picture = models.ImageField(null=True, blank=True, upload_to='images/')
    
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    
    
    objects = models.Manager()
    published = PublishedManager()
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    comments = forms.CharField(required=False,max_length=255,widget=forms.TextInput(attrs={'class':'form-control'}))
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email' ,'body']
        
        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm
from .models import Post, Comment


def search_post(request):
    posts = []
    query = None
    if request.method == 'POST':
        query = request.POST['query']
        posts = Post.published.annotate(
            search=SearchVector('title', 'body')
        ).filter(search=query)
    print(posts)
        
    return render(request, 'blog/search.html', {'posts':posts, 'query':query})



def recent_post(request):
    posts = Post.objects.all()[:2]
    tags = Tag.objects.all()
    
    most_commented_posts = Post.published.annotate(
        total_comments=Count('comments')
    ).order_by('-total_comments')[:4]
    
    return render(request, 'blog/recent_post.html', 
                  {'posts':posts, 'tags':tags, 
                   'most_commented_posts':most_commented_posts})


def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        body = request.POST['body']
        comment = Comment(name=name, email=email, body=body)
        comment.post = post
        comment.save()
        return redirect(post.get_absolute_url())
    
    return redirect('post_comment')


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            
            subject = f' {cd["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n{cd["name"]}\' comments: {cd["comments"]}'
            
            send_mail(subject, message, 'jamalghazniwal@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    
    return render(request, 'blog/post_share.html', {'form':form, 'sent':sent, 'post':post})
        
 

def home(request):
    post_list = Post.objects.all()
    return render(request, 'blog/home.html')


def post_list(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 4)
    page_number = request.GET.get('page', 1)
    try:
        page = paginator.page(page_number)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        page = paginator.page(1)
    return render(request, 'blog/post_list.html', {'post_list':post_list, 'page': page})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=post)
    comments = post.comments.filter(is_active=True)
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags','-publish')[:4]
    
    form = CommentForm() 
    
    return render(request, 'blog/post_detail.html', 
                  {'post':post, 'comments':comments, 'form':form,
                   'similar_posts':similar_posts})

templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>Blog | {% block title %} {% endblock title %}</title>
</head>
<body>
    {% include "blog/navbar.html" %}

    {% block content %}
    
    {% endblock content %}
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
</body>
</html>

templates/blog/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
    <section class="mt-5 py-5" id='header'>
        <div class="container">
            <div class="row gx-5 align-items-center">
                <div class="col-md-12 col-lg-5 offset-md-1 mt-4 mb-4">
                    <img src="{% static "images/h.svg" %}" class="img-fluid">
                </div>
                <div style="font-size:18px;" class="col-md-12 col-lg-6 ">
                    <h1>Expand Your Knowledge With Us</h1>
                    <p  class="my-3 text-muted">Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
                </div>
            </div>
        </div>
    </section>

      <section class="py-5 px-3">
        <h2 class="text-center text-center">Our Services</h2>
        <p class="my-3 text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente</p>
        <div class="row text-center p-5">
          <div class="col-md-6 col-lg-4">
            <div class="servise-box border-primary p-5">
              <h3>Create</h3>
              <p class="pt-3 pb-5">Lorem ipsum dolor sit amet ut voluptatum</p>
              <a class="read-more text-primary"><span>Read More</span></a>
            </div>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="servise-box border-success p-5">
              <h3>Share</h3>
              <p class="pt-3 pb-5">Lorem ipsum dolor sit amet ut voluptatum</p>
              <a class="read-more text-success"><span>Read More</span></a>
            </div>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="servise-box border-warning p-5">
              <h3>Comment</h3>
              <p class="pt-3 pb-5">Lorem ipsum dolor sit amet ut voluptatum</p>
              <a class="read-more text-warning"><span>Read More</span></a>
            </div>
          </div>
        </div>
      </section>


      <section class="my-5">
        <div class="container">
          <div class="row align-items-center gy-5">
            <div class="col-order_1 col-md-6">
              <h3 class="mb-3 fs-1"><b>Share what you know </b></h3>
              <p class="text-muted">Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
            </div>
            <div class="col-order_2 col-md-6">
                <img src="{% static "images/sk.svg" %}" class="img-fluid">
              </div>
          </div>
        </div>
      </section>

      <section class="py-5 px-3">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12 col-md-6">
              <h2 class="text-center lalezar">Frequently Asked Questions</h2>
              <p class="text-justify my-3">Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl Mauris neque quam</p>
            </div>
            <div class="col-12 col-md-6">
              <img src="{% static "images/faq.png" %}" class="img-fluid">
            </div>
            <div class="col-12">
              <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Mauris neque quam, fermentum ut nisl vitae
                    </button>
                  </h2>
                  <div id="collapseOne" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <p>
                        Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.
                      </p>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Fermentum ut nisl vitae, convallis maximus nisl
                    </button>
                  </h2>
                  <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Incidunt et ea quo dolore laudantium consectetur!
                    </button>
                  </h2>
                  <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="heading4">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse4" aria-expanded="false" aria-controls="collapseThree">
                        Totam reiciendis temporibus qui quibusdam
                    </button>
                  </h2>
                  <div id="collapse4" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="heading5">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse5" aria-expanded="false" aria-controls="collapse5">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit
                    </button>
                  </h2>
                  <div id="collapse5" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <strong>Sunt ut voluptatum</strong>eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      
      <footer class="py-5 px-3">
        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-5">
              <h4>www.myblog.com</h4>
              <p class="text-muted">incidunt et ea quo dolore laudantium consectetur!</p>
              <p>
                <a href="{% url "blog:post_feed" %}">
                  Subscribe to my RSS feed
                </a>
              </p>
            </div>
            <div class="col-lg-3 offset-lg-1">
              <h4 class="fw-bold border-bottom border-4 border-warning pb-3 w-75">Links</h4>
              <p>
                <a class="my-link" href="{% url "blog:home" %}">Home</a>
              </p><p>
                <a class="my-link" href="{% url "blog:post_list" %}">Posts</a>
              </p>
            </div>
            <div class="col-lg-3">
              <h4 class="fw-bold border-bottom border-4 border-success pb-3 w-75">Services</h4>
              <p>Educational Articles</p>
              <p>Add Articles</p>
              <p>Share Your Thoughts</p>
            </div>
          </div>
        </div>
      </footer>
{% endblock content %}

templates/blog/navbar.html
<nav id="my-nav" style="background-color: #ebf0fa;" class="navbar navbar-expand-md fixed-top mb-5">
    <div class="container">
      <a class="navbar-brand fs-3 lalezar fw-bold" href="#">My Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title fs-2 fw-bold" id="offcanvasNavbarLabel">My Blog</h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
            
            <li class="nav-item px-2">
              <a class="nav-link text-dark  " aria-current="page" href="{% url "blog:home" %}">Home</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link text-dark " aria-current="page" href="{% url "blog:post_list" %}">All Posts</a>
              </li>
            <li class="nav-item px-2">
                <a class="nav-link dropdown-toggle text-dark " href="#collapseExample" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="collapse" aria-expanded="false">
                  More
                </a>
                <div class="collapse position-ms-fixed" id="collapseExample">
                  <div class="course-list">
                    <div class="course-list-item">
                       <a href="{% url "blog:recent_post" %}" style="text-decoration:none;color:black;">
                        <span class="fw-bold mx-2">Recently Added Posts</span>
                      </a>
                    </div>
                    <div class="course-list-item">
                      <a href="{% url "blog:search_post" %}" style="text-decoration:none;color:black;">
                       <span class="fw-bold mx-2">Search Post</span>
                     </a>
                   </div>
                  </div>
                </div>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div id="scrollelem"></div>

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{post.title}}{% endblock title %}
{% comment %} <div class="col-xs-12 col-md-12 mb-3 w-100"> {% endcomment %}
{% block content %}
    <div style="margin-top: 90px;" class="container">
        <div class="row align-items-center">
            <div class="col-xs-12 col-md-12 col-lg-6 mb-5">
                <img src="{{ post.picture.url }}" class="card-img-top my-shadow" >
            </div>
            <div class="col-xs-12 col-md-12 col-lg-6 ">
                <div class="card-body">
                    <h5 class="card-title fw-bold my-margin pb-2">{{ post.title }}</h5>
                    <h5 class="card-title my-margin pt-2 text-muted">
                      Published {{ post.publish }} by<span class="">{{ post.author }},
                      </span>
                    </h5>
                    <p class="text-muted">
                      Tags: {{post.tags.all|join:", "}}
                    </p>
                    <p class="card-tex my-margint"> {{ post.body }}</p>
                    <div class="my-footer d-flex justify-content-between align-items-center">
                        <p class="fw-bold">
                            <a type="button" class="share-btn" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Add comment</a>
                             <a class="share-btn" href="{% url "blog:post_share" post.id %}">Share post</a>
                             {% with comments.count as total_comments %}
                                <a type="button" class="share-btn" data-bs-toggle="modal" data-bs-target="#exampleModali">Comments</a><span class=" badge rounded bg-dark">{{ total_comments }}</span>
                            {% endwith %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <h4>Posts with the same tag</h4>
        {% for post in similar_posts %}
          <a href="{{post.get_absolute_url}}">
            {{post.title}}<br>
          </a>
        {% empty %}
        <p>No similar post yet<p>
        {% endfor %}

    </div>


    <div class="modal modal-xl fade modal-fullscreen" id="exampleModali" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">All Comments</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body w-100">
                {% for comment in comments %}
                    <div class="card w-100">
                    <div class="card-header w-100">
                        Comment {{ forloop.counter }} by {{ comment.name }}
                    </div>
                    <div class="card-body w-100">
                        <h5 class="card-title">{{ comment.created }}</h5>
                        <p class="card-text">{{ comment.body|linebreaks }}</p>
                        {% comment %} <a href="#" class="share-btn">Go somewhere</a> {% endcomment %}
                    </div>
                    </div>
                    <br>
                {% empty %}
                    <p>There are no comments.</p>
                {% endfor %} 
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

<div class="modal fade mt-5 " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" >
      <div class="modal-content">
        <div class="modal-header ">
          <h5 class="modal-title" id="exampleModalLabel">What's in your mind?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url "blog:post_comment" post.id %}"  >
            {% csrf_token %}
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Name</label>
                <input required name='name' type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Email</label>
                <input required name='email' type="email" class="form-control" id="exampleInputPassword1">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3 ">
                <label for="exampleInputPassword1" class="form-label">Body</label>
                <input required name='body' type="text" class="form-control" id="exampleInputPassword1">
            </div>
            <input type="submit" class="btn btn-success btn-sm" value="Submit"/>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}
{% block title %}All Posts{% endblock title %}
{% block content %}
    <div style="margin-top: 90px;" class="container-fluid ">
        <div class="row mb-4 w-100 ">
            <div class="col my-width">
                <div class="col-xs-12 col-md-12 mb-3 ">
                    <div class="row w-100 mx-auto">
                        {% for post in page %}
                            <div class="col-xs-12 col-md-12 col-lg-6 col-xl-4 mb-3">
                                <div class="card my-shadow" >
                                    <div class="my-max-height">
                                        <img src="{{ post.picture.url }}" class="card-img-top img-fluid new-max-height" >
                                    </div>
                                    <div class="card-body">
                                        <h5 class="card-title fw-bold my-margin">{{ post.title }}</h5>
                                        <h5 class="card-title my-margin text-muted">Published {{ post.publish }} by {{ post.author }},</h5>
                                        <p class="text-muted">
                                            Tags: {{post.tags.all|join:", "}}
                                        </p>
                                        <p class="card-tex my-margint"> {{ post.body|markdown|truncatechars_html:100 }}</p>
                                        
                                        <div class="my-footer d-flex justify-content-between align-items-center">
                                            <a href="{{ post.get_absolute_url }}" id="read-btn">READ MORE ≫</a>
                                            {% with post.comments.count as total_comments %}
                                                <p class="fw-bold">Comments <span class=" badge rounded bg-dark">{{ total_comments }}</span> </p>
                                            {% endwith %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="container-fluid text-center">
        <div>
            <div>
                {% if page.has_previous %}
                    <a href="?page={{ page.previous_page_number }}" class="my-btn">Previous</a>
                {% endif %}
                {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="my-btn">Next »</a>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="">
            <p class="my-name mt-2 text-light">Ghazniwal Design</p>
        </div>
    </footer>
{% endblock content %}

templates/blog/post_share.html
{% extends "base.html" %}
{% load static %}
{% block title %}Share {{post.title}} {% endblock title %}

{% block content %}
<div class="container-fluid my-bg">
    <div class="container my-bg" style="margin-top:90px; margin-bottom:30px;">
        {% if sent %}
            <h1>E-mail successfully sent</h1>
        {% else %}
            <div class="row align-content-center">
                <div class="col-xs-12 col-md-5 col-lg-5">
                    <img class="img-fluid" src="{% static "images/s.svg" %}" />
                </div>
                <div class="col-xs-12 col-md-7 col-lg-7">
                    <h1>
                        Share "{{post.title}} by e-mail"
                    </h1>
                    <form method="POST">
                        {{form.as_p}}
                        {% csrf_token %}
                        {% comment %} <input class="send-email-btn" type='submit' value='Send e-mail' /> {% endcomment %}
                        <button type='submit' class="send-email-btn">Send e-mail</button>
                    </form>
                </div>
                
            </div>
        {% endif %}

    </div>
</div>
{% endblock content %}